[workspace]

resolver = "2"

members = [ "lib_app_state",
    'lib_config',
    'lib_crypto',
    'lib_error',
    'lib_middleware',
    'lib_redis',
    'lib_schema',
    'lib_sql_lib',
    'srv_backend',
]
