services:
  web_server_1:
    image: rust_web:latest
    container_name: web_server_1
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "postgres://postgres@host.docker.internal/sfi_web"
      APP_CONFIG: "/config/config.json"
    volumes:
      - ./:/config

  web_server_2:
    image: rust_web:latest
    container_name: web_server_2
    ports:
      - "9001:9000"
    environment:
      DATABASE_URL: "postgres://postgres@host.docker.internal/sfi_web"
      APP_CONFIG: "/config/config.json"
    volumes:
      - ./:/config
      
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
