[package]
name = "lib_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.107"
dotenv = "0.15.0"
log = "0.4.20"
