[package]
name = "lib_app_state"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { workspace = true }
uuid = { workspace = true }
deadpool-redis = { workspace = true }

lib_config = { path = "../lib_config" }
